apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: prod
bases:
  - https://github.com/agmsb/blueprints/team-seven/resources
patchesStrategicMerge:
- service.yaml
configMapGenerator:
- name: demo-feature
  literals:    
  - FEATURE="stable and reliable feature"